### ISSUE TITLE
BCDiceからガーデンオーダーが使えない

### ISSUE THREAD

**Issue by rail-rain** [torgtaitai/BCDice#20]
bcdice.rbやOnset!などからガーデンオーダーが使えません。
以下のコードをbcdiceCore.rbの2056行目に追加してテストしたところ、期待通りに動作しました。
```ruby
when /(^|\s)(GardenOrder)$/i
  require 'diceBot/GardenOrder'
  diceBot = GardenOrder.new
```
上記のコードをそのまま使って下さっても構いませんし、別の方法でも問題ありませんが、なんらかの対応をお願いします

**Comment by torgtaitai** [comment]
確かに指摘の通りでした。
対処方法を検討中ですので、修正版リリースをお待ちください。
指摘ありがとうございます！

**Comment by rail-rain** [comment]
ありがとうございます、気長にお待ちしております。

**Comment by ochaochaocha3** [comment]
92bba5e8975848e591c20955f5c1dea6d8020163 の修正はDiceBotLoader#loadUnknownGameに頼っているので、上のコードの方が良いのではないのでしょうか？（有効指定されていないゲームの指定を無視するのはもちろん必要な機能だと思いますが、それとは別の問題です）
